

- name: "configuration play." 
  hosts: all
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_MIGRATIONS_DIR: ./src/migrations
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    TYPEORM_HOST: database-2.cz1fxfqcgs9q.us-east-1.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: 1234abcd
    TYPEORM_DATABASE: glee
    
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for:
        timeout: 60

    # - name: "install python for Ansible."
    #   raw: 'cat < script.sh'
    #   args:
    #     executable: /bin/bash

  roles:
    - configure-server